# Generated by Django 2.1.5 on 2019-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_auto_20190128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file_upload1',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file_upload2',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file_upload3',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file_upload4',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file_upload5',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
